### ISSUE TITLE
Crash after any search query

### ISSUE THREAD

**Issue by t1meshift** [cfangmeier/tuijam#17]
I've installed tuijam from AUR.
Authentication works but if I try to find any song, it crashes with a log just like that:
```ERROR:root:No module named 'apiclient'
Traceback (most recent call last):
  File "/usr/bin/tuijam", line 1329, in main
    loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 1005, in run
    reraise(*exc_info)
  File "/usr/lib/python3.7/site-packages/urwid/compat.py", line 58, in reraise
    raise value
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 1018, in wrapper
    return f(*args,**kargs)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 938, in io_callback
    callback()
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/bin/tuijam", line 902, in keypress
    return self.focus.keypress(size, key)
  File "/usr/bin/tuijam", line 358, in keypress
    self.app.search(txt)
  File "/usr/bin/tuijam", line 985, in search
    ytvids = [YTVideo.from_dict(hit) for hit in self.youtube_search(query)[1]]
  File "/usr/bin/tuijam", line 956, in youtube_search
    from apiclient.discovery import build
ModuleNotFoundError: No module named 'apiclient'
```
[log.txt](https://github.com/cfangmeier/tuijam/files/2854186/log.txt)

**Comment by cfangmeier** [comment]
Thanks for reporting this. It looks like you don't have the google API python client installed. The AUR package (which I don't actually maintain) should include this as a dependency. In the mean time try installing `python-google-api-python-client` and see if it works for you.

**Comment by cfangmeier** [comment]
I posted a comment for the AUR package so hopefully it gets updated soon. Did installing that package work for you?

**Comment by klardotsh** [comment]
Somehow I missed the AUR email (or it got buried, or never showed up, or whatever), but I caught up with GitHub notifications and saw the thread here.

I've pushed an update to the [new 0.3.4 release](https://github.com/cfangmeier/tuijam/commit/4baed0da39c2db2ebb1e1d1ff1ca3e608c9aa05d) and added the new dependency. Holler in the AUR (or tag/email/whatever me here on GitHub) if things are still wonky. Cheers!

**Comment by klardotsh** [comment]
Also @cfangmeier if you'd prefer to maintain the AUR package yourself, let me know and I'll happily turn it over. Back when I started using this there was no package so I became the de-facto maintainer there I guess and didn't realize anyone else was actually using the `PKGBUILD` until recently!

Either way's fine by me. I've turned on notifications for this repo in GitHub so I _should_ see updates more frequently either way.

**Comment by cfangmeier** [comment]
@klardotsh Thanks for setting up the AUR package! I'll add a note to the readme that points to it. The current maintenance situation works for me. I expect that in the future there won't be a high frequency of releases anyway since TUIJam is, to me at least, feature complete.

In any case, I guess this issue is resolved so I'll close it here.
