### ISSUE TITLE
distribution was not found and is required by google-api-python-client

### ISSUE THREAD

**Issue by trsdln** [cfangmeier/tuijam#57]
After latest system upgrade (Archlinux/AUR package) I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/bin/tuijam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'google-api-core<2dev,>=1.13.0' distribution was not found and is required by google-api-python-client
```
I tried to reinstall package, but no luck. Also, installing via pip doesn't help because of https://github.com/cfangmeier/tuijam/issues/56

**Comment by trsdln** [comment]
problem got fixed by itself with next system upgrade :tada:
