### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by annata83** [cfangmeier/tuijam#58]
Hi There; I get errors from AUR ( there are 2 packages in AUR Both with same results) and pip;
Here is [AUR](https://www.pastebin.zone/PTZntgEs) Log output 
Here is [PIP](https://pastebin.zone/RE6utuJQ) Log Output

**Comment by cfangmeier** [comment]
Hi @annata83 . Normally I've seen this happen when I've installed a python package globally through pip. ie:

```
sudo pip install somepackage
```

Then, when you try to install the arch package `python-somepackage` there are file conflicts. The solution is to 

```
sudo pip uninstall somepackage
```

for each package that has conflicts. Eventually, it should install properly.

**Comment by annata83** [comment]
Hi @cfangmeier ; I did a full system reinstall; no pip yet in my system. Still getting:
```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup  # Always prefer setuptools over distutils
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 36, in <module>
    from setuptools import windows_support
  File "/usr/lib/python2.7/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/lib/python2.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
==> ERROR: A failure occurred in package_python2-mechanicalsoup().
    Aborting...
```

**Comment by cfangmeier** [comment]
What distro are you running? I'm surprised to see Python 2.7 being used here still. TUIJam requires Python >=3.7.

**Comment by annata83** [comment]
Arch Linuix over here.
I run :
- which pip
`pip not found`
- which python-pip
`python-pip not found`
- which python
`/usr/bin/python`
`Python 3.8.2`
---
I have no idea; I have see in some post about creating python environments or something like that.. Do you think that may Help?
To be honest I though pip came with python like npm comes with Node;

**Comment by cfangmeier** [comment]
Hmm. I had thought that pip had been included with python for a few versions now. I just checked on my Arch system and I do have the `python-pip` package installed; probably brought in as a dependency at some point. In any case, you will likely need the `python-pip` package to install tuijam.

> I have see in some post about creating python environments or something like that.. Do you think that may Help?

This shouldn't be necessary.  If you install the AUR package, TUIJam will be installed at the system level (ie. into `/usr/lib/python3.8/site-packages/` ) . Or wherever your system python is located (which is apparently 3.8.2... not sure why 2.7 was showing up before. Did you manually invoke python2 in the install?)

**Comment by annata83** [comment]
this is the procces I went thru to install:
![pic-full-200505-1858-42](https://user-images.githubusercontent.com/18301363/81120188-90301c00-8f02-11ea-8a35-8e131886a007.png)
As I see it the package Build ask for it right?

**Comment by cfangmeier** [comment]
Thanks for the info. It looks like there are a couple things happening here.

  - First, I think the previous error is due to a mismatch between `libffi` and `PyGObject`. On my Arch install, it works with `libffi==3.3-3` and `PyGObject==3.36.0`. Can you check what versions you have when the error shows up?

  - Next, As best I can tell, Python 2 is being brought in as a dependency of a dependency of `python-distribute`. It's presence shouldn't cause any issues since python 3 will still be the default on Arch.

**Comment by annata83** [comment]
@cfangmeier ; I check and libffi is not on my system and neither is PyGObject;
should I try to add libffi and try again? Also should libffi be added as dependency to?

**Comment by annata83** [comment]
I did Install libfii and try Again:

```
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import setup  # Always prefer setuptools over distutils
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 19, in <module>
    from setuptools.dist import Distribution
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
    from setuptools import windows_support
  File "/usr/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
==> ERROR: A failure occurred in check().
    Aborting...
checking dependencies...
:: gtk2 optionally requires python2: gtk-builder-convert
:: gvim optionally requires python2: Python 2 language support
:: libnewt optionally requires python2: libnewt support with the _snack module
:: libproxy optionally requires python2: Python 2.x bindings
:: python-pywal optionally requires python2: reload gtk2 themes on the fly

Packages (7) python2-2.7.18-1  python2-appdirs-1.4.3-5  python2-ordered-set-3.1.1-1  python2-packaging-20.3-1  python2-pyparsing-2.4.7-1
             python2-setuptools-2:44.1.0-1  python2-six-1.14.0-1

Total Removed Size:  78.34 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/7) removing python2-setuptools                                                                [########################################################] 100%
(2/7) removing python2-ordered-set                                                               [########################################################] 100%
(3/7) removing python2-packaging                                                                 [########################################################] 100%
(4/7) removing python2-six                                                                       [########################################################] 100%
(5/7) removing python2-pyparsing                                                                 [########################################################] 100%
(6/7) removing python2-appdirs                                                                   [########################################################] 100%
(7/7) removing python2                                                                           [########################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```
