### ISSUE TITLE
Check if config directory exists

### ISSUE THREAD

**Issue by opcon** [cfangmeier/tuijam#7]
Hi, I just installed tuijam for the first time, and it crashed with the following traceback:

```
Traceback (most recent call last):
  File "/home/<username>/.local/bin/tuijam", line 4, in <module>
    __import__('pkg_resources').run_script('tuijam==0.1.0', 'tuijam')
  File "/home/<username>/anaconda3/envs/gmusic/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/<username>/anaconda3/envs/gmusic/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/home/<username>/.local/lib/python3.6/site-packages/tuijam-0.1.0-py3.6.egg/EGG-INFO/scripts/tuijam", line 875, in <module>
  File "/home/<username>/.local/lib/python3.6/site-packages/tuijam-0.1.0-py3.6.egg/EGG-INFO/scripts/tuijam", line 852, in main
  File "/home/<username>/anaconda3/envs/gmusic/lib/python3.6/logging/__init__.py", line 1806, in basicConfig
    h = FileHandler(filename, mode)
  File "/home/<username>/anaconda3/envs/gmusic/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/<username>/anaconda3/envs/gmusic/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/<username>/.config/tuijam/log.txt'

```

I created the ~/.config/tuijam directory which fixed the problem.

**Comment by cfangmeier** [comment]
Thanks for reporting this. It should be fixed now.
