### ISSUE TITLE
Resizing tuijam causes a crash. 

### ISSUE THREAD

**Issue by Moovlin** [cfangmeier/tuijam#8]
I use i3 as a window manager and also use tuijam as a floating window. I was resizing the window to a very small size when suddenly the player crashed. I repeated this over and over again about 3 times. I've included the log. It appears to be an issue with the rendering of the actual screen. 

> ERROR:root:'utf-8' codec can't decode byte 0xe2 in position 50: unexpected end of data
Traceback (most recent call last):
  File "/home/sinn3r/tuijam/tuijam", line 869, in main
    loop.run()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 710, in _loop
    self._entering_idle()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 671, in _entering_idle
    callback()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 564, in entering_idle
    self.draw_screen()
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/main_loop.py", line 579, in draw_screen
    self.screen.draw_screen(self.screen_size, canvas)
  File "/home/sinn3r/.local/lib/python3.6/site-packages/urwid-1.3.1-py3.6-linux-x86_64.egg/urwid/raw_display.py", line 838, in draw_screen
    l = l.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 50: unexpected end of data

**Comment by cfangmeier** [comment]
Thanks for reporting this!
My own setup (Gnome/termite/tmux) is a bit different than yours, but I was unable to reproduce this error locally. What terminal emulator are you using? And does other unicode work in your terminal (for example the play/stop icon in the status bar)?

I'm guessing that this is actually a problem with [urwid](https://github.com/urwid/urwid), but I was using quite an old version (1.3), and I think newer versions have better unicode handling. I just pushed a commit which updates to urwid 2.0.1. So if you like, try reinstalling tuijam and see if the problem persists.

**Comment by Moovlin** [comment]
I'm using gnome terminal. So it supports Unicode and tuijam was working fine as long as the window didn't reach an extremely small size. I didn't do any extreme testing but that seems to have fixed the issue. Thanks for the quick fix!
